### ISSUE TITLE
conektaIframeContainer does not exist

### ISSUE THREAD

**Issue by miguel-tks** [conekta/conekta_prestashop#103]
Hola a todos.

Espero que alguien me pueda ayudar, estoy implementando el plugin de conekta la versión 1.1.0 pero me manda el siguiente error cuando intento realizar el pedido y selecciono la opción de "Pago por medio de Conekta":

**_Uncaught Error: Document is ready and element #conektaIframeContainer does not exist
    at conekta-checkout.min.js:1:32661_**

Estas son las versiones de software con las que estoy trabajando:

PHP: 7.4.26
MySQL: 5.7.36
Prestashop: 1.7.8.2

**ERROR**

![error](https://user-images.githubusercontent.com/6466606/177924336-3a16bc92-b58a-4875-a987-6ea4d6c4611e.jpg)

**STACK** 

![software](https://user-images.githubusercontent.com/6466606/177924338-4ac78843-55a5-4f84-a5ea-1cbcce87fdff.jpg)

De antemano muchas gracias por su ayuda.

**Comment by ElvisHeredia** [comment]
Puedes probar con este [conekta.zip](https://github.com/conekta/conekta_prestashop/files/9923279/conekta.zip), contiene la última versión disponible.

**Comment by gorkatrevino** [comment]
> Puedes probar con este [conekta.zip](https://github.com/conekta/conekta_prestashop/files/9923279/conekta.zip), contiene la última versión disponible.

Hola, nos recomendaron en soporte técnico actualizar el módulo debido a una diferencia de cobro que generó Conekta (La versión que tenemos en este momento es la 1.1.0 en PS 1.7.6.7). Me encuentro con el mismo error, intentando actualizar a 2.3.7 (release) o 2.3.3 (la que comparten en la respuesta). Mismo error en consola cuando llego al paso del método de pago en checkout, y ya descartamos que conektapaymentprestashop (el nombre del módulo previo) no guardara información en la DB que esté reutilizando el nuevo módulo y que eso le causara conflictos.

Esta es la configuracion con la que estoy trabajando:

- PHP: 7.2.34
- MySQL: 8.0.35
- PrestaShop: 1.7.6.7 (Multitienda activado)

![conekta-error2](https://github.com/conekta/conekta_prestashop/assets/108596802/db3adc91-e83d-4f78-bcce-65e50ea7a02f)
![conekta-error](https://github.com/conekta/conekta_prestashop/assets/108596802/94fe4e3a-d22a-47ca-b42a-c1dd042395f0)
