### ISSUE TITLE
PrestaShop 1.7.8.x

### ISSUE THREAD

**Issue by lizg0** [conekta/conekta_prestashop#108]
No se puede instalar en 1.7.8.7

Información del servidor: Linux #1 SMP Fri Jan 28 05:34:34 EST 2022 x86_64
Versión del software del servidor: Apache
Versión de PHP: 7.2.34
Límite de memoria: 1024M

Tiempo máx. de ejecución: 1500

**Comment by jmdiazlr** [comment]
Igual, no funciona... soy programador aunque no conosco mucho de php, pero al ver el fuente es evidente que el modulo no funciona por errores realmente infantiles, lo que me lleva a pensar que intencionalmente no funciona, que los programadores son los mismos que venden otro plugin que esta en el marketplace de prestasho. Se supone que este plugin es oficial de Conekta... hice cambios minimos para que instalara pero presenta otros erroes, al pasar a pagar dice "Desafortunadamente no hay metodos de pago" aun cuando tengo los activados otros 2 metodos de pago que trae prestashop por default... si deshabilito este plugin todo vuelve a la normalidad... y corregir esta fuera de mi alcance porque ademas de PHP se involucra como esta programado prestashop y en ambas cosas soy novado. Pero es una lastima que Conekta no le de importancia facilitar la integracion a sus potenciales clientes. Probare STRIPE como algun otro usuario desilucionado comento antes.

**Comment by jmdiazlr** [comment]
Probe la version 1.1.1 desde el market place de prestshop... mismo comportamiento.... probare en una instalcion nueva de prestashop a ver si es algo de mi instalacion.

Tambien probe descargar el release del 6 de sep, el ultimo, y los anteriores... esos estan peor, ni siquiera contienen el archivo principal conekta.php requerido por prestashop... este plugin es un fiasco.

**Comment by ElvisHeredia** [comment]
@lizg0 le comparto el archivo zip del último release disponible, este fue testeado en la versión que mencionas
[conekta.zip](https://github.com/conekta/conekta_prestashop/files/9923297/conekta.zip)
Estamos atentos a cualquier duda
