### ISSUE TITLE
No es posible instalar: This file does not seem to be a valid module zip

### ISSUE THREAD

**Issue by andresadanmx** [conekta/conekta_prestashop#110]
Hola, no me ha sido posible instalar el módulo en su última versión 2.3.3, al tratar de hacerlo obtengo esto en modo depuración: "This file does not seem to be a valid module zip"

Al revisar la carpeta de los archivos, he mirado que hace falta el archivo conektapaymentsprestashop.php

Saludos

**Comment by ElvisHeredia** [comment]
Buen día, esta es la última versión disponible para instalación [conekta.zip](https://github.com/conekta/conekta_prestashop/files/9923279/conekta.zip)
