### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by jmdiazlr** [conekta/conekta_prestashop#111]
No instala, las instrucciones son imprecisas, las versiones en el market place tampoco funcionan, tampoco los "releases anteriores" es un fiasco

**Comment by ElvisHeredia** [comment]
@jmdiazlr le comparto el archivo zip para que le sea mas fácil instalar la última versión disponible 
[conekta.zip](https://github.com/conekta/conekta_prestashop/files/9923279/conekta.zip)
