### ISSUE TITLE
Can not be installed on PS 8.1

### ISSUE THREAD

**Issue by wwwsurfer** [conekta/conekta_prestashop#120]
Conekta says you must use latest PS version, so using this version with PS 8.1.7 and php 8.1 can not be even installed. 

"Installation of module failed. This file does not seem to be a valid module zip"

Is there a chance to get a new version for PS 8.1 or 8.2 Thanks

**Comment by fcarrero** [comment]
hi @wwwsurfer  he have launched a new version 3.0.0 https://github.com/conekta/conekta_prestashop/releases/tag/3.0.0 
which supports prestashop 8.0 and php >= 7.4
