### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by wwwsurfer** [conekta/conekta_prestashop#124]
Hello. Does not work. Can not be installed

_"Installation of module failed. This file does not seem to be a valid module zip"_

Dowloaded 3..0.0 zip file  from here.

Prestashop 8.2 & php 8.1

**Comment by fcarrero** [comment]
inside of your zip you should have a folder named "conekta"
![image](https://github.com/user-attachments/assets/468fa2e5-b1dd-4015-9c7e-151e89590a76)

![image](https://github.com/user-attachments/assets/7caced37-050d-4d3c-94f6-5441cedcce63)


[zip source](https://github.com/conekta/conekta_prestashop/archive/refs/tags/3.0.0.zip)

[conekta.zip](https://github.com/user-attachments/files/17549248/conekta.zip)

**Comment by wwwsurfer** [comment]
Thx. The one on the project is not packed that way. See attached picture. However I downloaded now from your link above and it is installable. Thank you very much.

![pack](https://github.com/user-attachments/assets/83280722-a95f-4cd3-a8f9-2dcdcf4b4c5d)

**Comment by fcarrero** [comment]
great
