### ISSUE TITLE
Instalar en Servidor Local

### ISSUE THREAD

**Issue by AntonioCahuich** [conekta/conekta_prestashop#39]
Realize la instalacion en un servidor local, pero al configurar el WebHook me aparece un warning con: "Unauthorized access" y me dice que ya se puede hacer uso del modulo
![screenshot_3](https://user-images.githubusercontent.com/12449488/29437735-19ec52b8-8378-11e7-8261-db309d4d74eb.png)
pero al realizar la compra no me aparece la opción de pago del plugin.

¿El dilema sera por estar instalado en Local?

**Comment by eduardoconekta** [comment]
Eso no debería de afectar los metodos de pago para que sean visibles, estas en modo debug o producción en prestashop ? , es la version 1.7 ? , revisaste en tu admin de conekta que se hubiera registrado el webhook ? @AntonioCahuich

**Comment by AntonioCahuich** [comment]
1. Modo debug
2. Si es version 1.7
3. Uso este webhook
    http://localhost/'nombre-de-tienda'/modules/conektaprestashop/notification.php
4. (Posible Error) Puese palabaras random de prueba, si fuese el caso, los key de prueba se obtienen desde la cuenta en Conekta?
![screenshot_4](https://user-images.githubusercontent.com/12449488/29468260-2d99f770-8409-11e7-9241-3bb9ef39a4f8.png)
   que casillas he de rellenar para pruebas?

**Comment by JoValo** [comment]
@AntonioCahuich en **Test Private Key** y **Test Public Key** van las keys de pruebas de tu admin de [Conekta](https://admin.conekta.com/settings/keys), las **Live Public/Private** son los campos que debes llenar con las keys de producción de Conekta.

**Comment by eduardoconekta** [comment]
Otro señalamiento, es que si instalaste manualmente otra version de nuestro plugin borrarlo/desinstalarlo y hacer la instalación nueva de la version para 1.7 ya que nosotros dejamos de pedir signature test key y signature live key, posiblemente sera un feature en las siguientes versiones pero actualmente esta en la version 1.6 
![captura de pantalla 2017-08-18 a la s 11 56 29](https://user-images.githubusercontent.com/26972091/29469067-5769fe6c-840c-11e7-8239-26dc423625bb.png)

**Comment by AntonioCahuich** [comment]
De acuerdo. Muchas gracias por su apoyo. Se instalo la version de 1.7, pero volvere a descargar para confirmar.
