### ISSUE TITLE
Produccion no me funciona

### ISSUE THREAD

**Issue by simongas** [conekta/conekta_prestashop#48]
Todos los pedidos me los manda a pruebas, aunque tenga en el plugin activado el modo produccion y en la cuenta de conekta tambien esta activado el modo produccion. Hay algo que se me este pasando?

**Comment by Janee** [comment]
Hola @simongas ¿estás utilizando la versión de Prestashop 1.7? Este repo es sólo para esa versión. Si cuentas con una versión inferior este es el repo: https://github.com/conekta/conektaprestashop

**Comment by simongas** [comment]
Si estoy utilizando la version 1.7.*
Tambien nos comunicamos con soporte al cliente de conekta y al parecer ya quedo, no era problema del plugin. Muchas gracias.
