### ISSUE TITLE
Error en instalación

### ISSUE THREAD

**Issue by AntonioCahuich** [conekta/conekta_prestashop#53]
Versión de PrestaShop: 1.7.2.4

Al intentar instalar el modulo me marca un error en modo Debug, al parecer es una sección de codigo, que al comentarlo se logra instalar correctamente.

![image](https://user-images.githubusercontent.com/12449488/32383838-b472b3fc-c07e-11e7-9381-82dd62444396.png)

**Comment by eduardoconekta** [comment]
@AntonioCahuich este error es al subir el modulo a prestashop ?

**Comment by AntonioCahuich** [comment]
A subir el modulo a prestashop

**Comment by AntonioCahuich** [comment]
Lo obtuve de clonar el repositorio de Github. Actualmente el modulo esta instalado, pero tuve que comentar esa sección por que el Debug me marcaba que eso lo estaba causando. Recreare el proceso en una instalación limpia y adjuntare las capturas.
