### ISSUE TITLE
Imposible instalar modulo

### ISSUE THREAD

**Issue by edusanch913** [conekta/conekta_prestashop#54]
Hemos intentado instalar su modulo y marca error.

Estamos usando la versión de PrestaShop 1.7.2
PHP 5.6.31
Servidor Linux info 3.0 

La versión del Plugin que intentamos instalar son dos las cuales se descargaron de esta página:

https://github.com/conekta/conekta_prestashop/releases

Que es la última versión v1.2.0
Y también intentamos con la versión anterior v1.1.0

Y con ambas nos fue imposible instalar el modulo, como les mencionamos en un correo, hice lo que indican en las instrucciones que es comprimir los archivos en un archivo ZIP con el nombre conekta_prestashop pero no se puede!!

Ya intentamos poner el nombre de la carpeta comprimida solamente “conekta”, “conekta_prestashop-master”, “conekta_master” y marca que la subida ha fallado. Realmente es el mismo proceso de instalación de cualquier modulo, pero no es posible con el suyo. Menciono esto ya que en muchas ocasiones no se carga un modulo correctamente debido al nombre que tiene el archivo .ZIP

Esperamos puedan realizar alguna actualización para nuestra versión de PrestaShop o que nos indiquen como realizar la correcta instalación.

Quedamos atentos a su apoyo, saludos!

**Comment by mauroarcet** [comment]
Hola @edusanch913 nuestro módulo para Prestashop 1.7 requiere una versión de PHP > 7
