### ISSUE TITLE
Error al pagar con tarjeta

### ISSUE THREAD

**Issue by AldoAlbert** [conekta/conekta_prestashop#55]
Hola, estoy tratando de usar el pago con tarjeta de crédito, con pago en oxxo funciona bien pero cuando selecciono la tarjeta y meto los datos solo recarga la página y no cambia el estatus del carrito ni de la compra. Al hacer el pago, la página redirige al index y agrega el token de la tarjeta a la url pero no se hace la transacción. Estamos en modo de pruebas.

Detalles:
Versión de PrestaShop: 1.7.2.3
Versión de MySQL: 5.7.21
Versión PHP: 7.0.22
Versión de plugin: v1.1.0
Webhook: https://midominio/modules/conekta_prestashop/notification.php

**Comment by eduardoconekta** [comment]
@AldoAlbert , @ohlalo10 desde donde descargaron el plugin? desde marketplace?, una disculpa por la demora

**Comment by ohlalo10** [comment]
Que tal eduardo, en mi caso lo descargue de github..del enlace de conekta... es la version 1.1.0, y si tiene el archivo notification.php

Saludos

**Comment by eduardoconekta** [comment]
@ohlalo10 voy a intentar reproducir el error descargando el código como lo indicas y te comento los resultados, en caso de requerirse un fix lo estaré linkeando aquí para que estes enterado cuando se libere :)

**Comment by leofischer** [comment]
Adding to Zendesk

**Comment by luisSpring** [comment]
Hola @AldoAlbert . 

¿Lograste solucionar el issue? Desafortunadamente me ocurre lo mismo con la última versión del módulo y la versión 1.7.6

**Comment by silvaGarduno** [comment]
Hola @luisSpring , podrías intentar con está versión por favor.

https://github.com/conekta/conekta_prestashop/tree/prestashop-1-7-6-0

**Comment by luisSpring** [comment]
Gracias por tu ayuda @silvaGarduno 

Lo probé pero hace lo mismo, al realizar el pago redireccióna al home sin modificar el carrito de compras.
Mi hook está referenciado a **/conektapaymentsprestashop/notification.php**   y en el panel de conekta se muestra como activo.  

 En el inspector puedo ver que al realizar el pago redirecciona a 
 ` https://d3fxnri0mz3rya.cloudfront.net/antifraud/key_MAEU2fsZNtZwauDmrmCDoNw.js?callback=conekta_antifraud_config_jsonp `     

y luego redirecciona a     

**improve/modules/manage?_token=qlXwU6pWZjy99Pcb7Nk3CJCG1irKsKdTLXq1OV0oWMw**

al parecer no existe la ruta y por eso muestra el index.

Muy raro todo esto.

**Comment by silvaGarduno** [comment]
@luisSpring si esta raro el error, el problema es que de mi lado no logró replicar lo mismo, que configuración tienes en tu plataforma? plugins, versiones, etc.

**Comment by luisSpring** [comment]
@silvaGarduno  Tengo el plugin de pago de paypal (deshabilitado)
la versión de prestashop es 1.7.6.2
y bueno.. es todo lo que tengo

**Comment by silvaGarduno** [comment]
has intentado con alguna otra versión de prestashop? que versión tienes de php?

**Comment by luisSpring** [comment]
PHP version: 5.6.40

**Comment by silvaGarduno** [comment]
@luisSpring  has intentado con una versión mayor a php 7?

**Comment by luisSpring** [comment]
Hola, ha pasado tiempo.

Me rendí con conekta y opté por paypal. Actualicé mi versión de PHP e incluso la versión menor de prestashop. Pero el error sigue siendo el mismo. Tú has logrado algún avance?

Ahora mi versión de PHP es  7.3.

**Comment by silvaGarduno** [comment]
Hola @luisSpring, yo tengo una versión de prestashop 7.6.5 y php 7.3 y funciona correctamente, en tu caso no se que a que se deba, puede ser algún bloqueo por parte de prestashop, has checado la "herramienta de desarrollador" que existe en el navegador? tal vez ahí nos pueda dar algún error o alguna pista para saber por donde va

**Comment by LuisHCB** [comment]
Hola. Al fin, después de leerme el código, llegue a la solución con la versión 1.7.6.2. No fueron grandes cambios por lo que intentaré un pull request.

**Comment by KikinLey182** [comment]
Hola, creo que ya resolvi el issue es cosa de que lo prueben y me validen si les funciona, aunque esto me esta dando dolor de cabeza porque me ocasiona problemas con paypal:

Si tienes desactivadas las url amigables el pago con tarjeta no funciona, si lo activas deja de trabajar paypal o al menos eso me pasa a mi.

**Comment by LuisHCB** [comment]
> Hola, creo que ya resolvi el issue es cosa de que lo prueben y me validen si les funciona, aunque esto me esta dando dolor de cabeza porque me ocasiona problemas con paypal:
> 
> Si tienes desactivadas las url amigables el pago con tarjeta no funciona, si lo activas deja de trabajar paypal o al menos eso me pasa a mi.

**Comment by LuisHCB** [comment]
Saludos KikinLey182. En mi caso, para resolver el issue modifiqué el código del modulo.

**Comment by KikinLey182** [comment]
> Saludos KikinLey182. En mi caso, para resolver el issue modifiqué el código del modulo.

Que modificaste del modulo para que pueda funcionar sin problema? 

Saludos!
