### ISSUE TITLE
Prestashop 1.7.4.2

### ISSUE THREAD

**Issue by HumbertoSa3nz** [conekta/conekta_prestashop#61]
No puedo instalar el modulo en mi version de prestashop que es la 1.7.4.2

**Comment by morfin** [comment]
1) Descarga conekta_prestashop-master.zip
2) Extrae el zip. Te dará una carpeta llamada "conekta_prestashop-master"
3) Renombra esa carpeta a "conekta_prestashop"
4) Zipea esa carpeta, te generará el archivo "conekta_prestashop.zip"
5) Ese es el archivo que debes usar para instalar el módulo en el panel de control de Prestashop.
