### ISSUE TITLE
PrestaShop 1.7.5

### ISSUE THREAD

**Issue by managermedia** [conekta/conekta_prestashop#63]
No se puede instalar modulo en PrestaShop 1.7.5

**Comment by morfin** [comment]
1) Descarga conekta_prestashop-master.zip
2) Extrae el zip. Te dará una carpeta llamada "conekta_prestashop-master"
3) Renombra esa carpeta a "conekta_prestashop"
4) Zipea esa carpeta, te generará el archivo "conekta_prestashop.zip"
5) Ese es el archivo que debes usar para instalar el módulo en el panel de control de Prestashop.
