### ISSUE TITLE
El token no existe

### ISSUE THREAD

**Issue by netronicus** [conekta/conekta_prestashop#64]
El módulo está correctamente instalado y configurado en prestashop 1.7.4.3, php 7.1, trato de hacer el proceso de compra en sandbox con tarjeta, procedo con la compra y sólo se recarga y me muestra el error de "El token no existe".
El error sólo se muestra en pago con tarjeta, el pago en oxxo si funciona correctamente.
Por otra parte, el webhook, según su documentación debe ser agregado de la siguiente manera:

https://(url_de_tu_sitio)/conekta_prestashop/notification.php

pero no funciona, funciona si se agrega así:

https://(url_de_tu_sitio)/modules/conekta_prestashop/notification.php

y si el _PS_MODE_DEV_ está en true, es imposible realizar la conexión ya que devuelve error 

(1/1) ContextErrorExceptionNotice: Undefined index: HTTP_DIGEST
--
in notification.php line 23

**Comment by silvaGarduno** [comment]
Hola @netronicus 

Tienes razón en cuanto a la configuración del WebHook, ese es un error de nuestra parte en la documentación.

Para el problema del "Token" posiblemente este fallando al llamar la libreria de Conekta.js, necesitas revisar en la opción de "Herramientas del desarrollador" de tu navegador web para ver que error te arroja al hacer esa llamada.
