### ISSUE TITLE
No aplica descuento por cupón

### ISSUE THREAD

**Issue by Aszacx** [conekta/conekta_prestashop#65]
Hola, estoy teniendo problemas en los cargos con TC y TD cuando los clientes utilizan un cupón de descuento, el monto al pagar se muestra de manera correcta en prestashop, pero al hacer el cargo lo realiza al 100%, he revisado las notificaciones de la petición al API y recibe el monto sin el descuento, se debe a una configuración mía?

Espero puedan orientarme, gracias. 

![1](https://user-images.githubusercontent.com/7471582/55853061-0a864500-5b25-11e9-8144-32258059bea8.PNG)
![2](https://user-images.githubusercontent.com/7471582/55853062-0a864500-5b25-11e9-9d67-0b1ee03bb91e.PNG)
![3](https://user-images.githubusercontent.com/7471582/55853063-0a864500-5b25-11e9-8a16-be6ad9a71417.PNG)

**Comment by angelsoria** [comment]
Hola.

Para solventar este issue, debes modificar los archivos:

/conekta_prestashop.php
Linea 954: $discounts = $cart->getDiscounts();
Remplazar por: $discounts = $cart->getCartRules();

/model/Config.php
Linea 80:  'amount' => (string) $cart->getOrderTotal(true, Cart::ONLY_DISCOUNTS) * 100,
Reemplazar por: 'amount' => (string) $discount['value_real'] * 100,

Como dato adicional algunos descuentos no tienen "codigo" de descuento te recomiendo en:
/model/Config.php
Linea 79: 'code'   => $discount['code'],
Reemplazar:  'code'   => $discount['name'],

Saludos

**Comment by leofischer** [comment]
@Conekta-supp

**Comment by leofischer** [comment]
@Conekta-supp

**Comment by silvaGarduno** [comment]
Hola @Aszacx 

Puedes usar la siguiente version
https://github.com/conekta/conekta_prestashop/tree/prestashop-1-7-6-0

Descarga el zip y realiza nuevamente la prueba.

saludos

**Comment by sloaxleak** [comment]
> Hola @Aszacx
> 
> Puedes usar la siguiente version
> https://github.com/conekta/conekta_prestashop/tree/prestashop-1-7-6-0
> 
> Descarga el zip y realiza nuevamente la prueba.
> 
> saludos

Hola @silvaGarduno  Intento instalar el ZIP y marca error y error, ¿alguna sugerencia? ¿Funciona con 1.7.5.2?

**Comment by sloaxleak** [comment]
> Hola, estoy teniendo problemas en los cargos con TC y TD cuando los clientes utilizan un cupón de descuento, el monto al pagar se muestra de manera correcta en prestashop, pero al hacer el cargo lo realiza al 100%, he revisado las notificaciones de la petición al API y recibe el monto sin el descuento, se debe a una configuración mía?
> 
> Espero puedan orientarme, gracias.
> 
> ![1](https://user-images.githubusercontent.com/7471582/55853061-0a864500-5b25-11e9-8144-32258059bea8.PNG)
> ![2](https://user-images.githubusercontent.com/7471582/55853062-0a864500-5b25-11e9-9d67-0b1ee03bb91e.PNG)
> ![3](https://user-images.githubusercontent.com/7471582/55853063-0a864500-5b25-11e9-8a16-be6ad9a71417.PNG)

Hola, ¿Cómo lo solucionaste? tengo exactamente el mismo problema.

**Comment by silvaGarduno** [comment]
Hola @sloaxleak, al descargar el plugin, obtendremos un archivo .zip. Deberás descomprimir el archivo, y cambiar el nombre que tenga por "conektapaymentsprestashop". Después vuelve a comprimir la carpeta en un .zip, ya con eso podrás subir el plugin a tu tienda y es el que tiene la solución para el problema de cupones.

**Comment by sloaxleak** [comment]
Hola @silvaGarduno  ¿sabes de casualidad cuál es la última versión compatible con PS 1.7.5.1?
