### ISSUE TITLE
Problema al  realizar pago

### ISSUE THREAD

**Issue by stylder** [conekta/conekta_prestashop#79]
Problema al querer realizar un pago, me regresa el siguiente error:

/en/module/conekta_prestashop/validation?type=cash
Request Method: POST
Status Code: 302 Moved Temporarily
Remote Address: 174.136.30.134:443
Referrer Policy: no-referrer-when-downgrade

conekta_error=1&message=carrier"%20is%20too%20short.%20#conekta_error

**Comment by silvaGarduno** [comment]
Hola @stylder, al parecer por el error "conekta_error=1&message=carrier"%20is%20too%20short.%20#conekta_error", menciona que el nombre del carrier es muy corto, podrías colocar un nombre más largo, que sea mayor a 5 caracteres por favor.

**Comment by stylder** [comment]
@silvaGarduno  cuál es la solución ya que el nombre del carrier ya lo cambié

![image](https://user-images.githubusercontent.com/6990509/88683827-d89e4680-d0b9-11ea-8a93-780e2b6511ea.png)

**Comment by silvaGarduno** [comment]
@stylder la parte de carrier (transporte) se configura en tu tienda prestashop no es en la configuración del plugin de conekta.
