### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by CrashingLynx** [conekta/conekta_prestashop#95]
Hola, se implementó Conekta en la versión más reciente de Prestashop (1.7.7.4) pero tiene varios errores en el checkout.

1. Al elegir el método de pago, se despliega el iframe con un botón, el cuál interfiere con el de Prestashop y para el usuario es algo confuso.
2. Cuando se genera la orden en el botón interno (color morado) y después se da clic en Realizar Pedido de Prestashop, regresa el error: Could not get the id of ConektaResource instance
3. Al pagar con tarjeta, se tiene que hacer dentro del iframe, de lo contrario, regresa el mismo error.

**Comment by stylder** [comment]
.

**Comment by stylder** [comment]
Tengo el mismo problema :(
